title: MedNeed Workshop for Medical Care Providers
description: > # this means to ignore newlines until "baseurl:"
  Join us on this edition of MedNeed Workshop for medical care providers and stakeholders to gain in-depth knowledge and access to financing strategies and resources for payment of medicines, equipment and supplies needed for quality and affordable medical care. Participants equally learn about innovative cost-saving tools for medical practice and research and have the opportunity to get live answers on solutions provided by MedNeed and partners. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://workshop.medneed.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/medneedservice
  - title: linkedin
    url: https://www.linkedin.com/company/medneedservice/
  - title: instagram
    url: https://www.instagram.com/medneedservice/"
  - title: youtube
    url: https://youtube.com



# Build settings
markdown: kramdown
permalink: pretty