title: Medneed Workshop | Resources for Affordable Stroke Care 
description: > # this means to ignore newlines until "baseurl:"
  Join us on Medneed Workshop, designed as a high-impact and readily accessible meeting for medical care providers to gain deeper insights on helpful resources for affordable stroke care. Participants equally learn about innovative cost-saving tools for overall medical practice and research and have the opportunity to get live answers on solutions from Medneed and partners.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://workshop.medneed.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/company/medneedservice/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/medneedservice
  - title: linkedin
    url: https://www.linkedin.com/company/medneedservice/
  - title: instagram
    url: https://www.instagram.com/medneedservice/
  - title: youtube
    url: https://www.youtube.com/channel/UC0T29j9UH0W_PO08lljGxQA



# Build settings
markdown: kramdown
permalink: pretty